# Generated by Django 5.1.6 on 2025-03-04 21:27

import django.contrib.auth.mixins
import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=16, verbose_name='username')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is_verified')),
            ],
            options={
                'verbose_name': ('users',),
                'verbose_name_plural': ('users',),
                'unique_together': {('username', 'email')},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
            managers=[
                ('object', users.managers.UserManager()),
            ],
        ),
    ]
